# Dockerfile.worker
FROM node:18-bullseye-slim

# install the Docker CLI
RUN apt-get update \
 && apt-get install -y --no-install-recommends docker.io \
 && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY package*.json ./
RUN npm ci --only=production

COPY . .

CMD ["node", "src/workers/submissionWorker.js"]
