FROM node:18-alpine as builder

WORKDIR /app
COPY package*.json ./
RUN npm ci --only=production
COPY . .

FROM docker:24-cli-alpine

WORKDIR /app
COPY --from=builder /app /app

CMD ["node", "src/workers/submissionWorker.js"]
